# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
      - image: circleci/node:8.0
    steps:
    - checkout
    ## background your server
    - run:
        command: npm install --save-dev cypress
        background: true
    - run:
        command: npm run dev
        background: true
    - run: $(npm bin)/cypress verify
    - run: $(npm bin)/cypress run
