# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # using custom image; see .circleci/images/primary/Dockerfile
      - image: laurenc/node-cypress:latest
    steps:
      - checkout
      ## background your server
      - run:
          command: |
            npm run pretest
      - run: 
          working_directory: ~/cypress-tutorial-build-todo-starter
          command: ./node_modules/.bin/cypress run
