# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
      ## background your server
      - run:
          command: |
            npm init -y
            npm install
            npm run pretest
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      # - run:
      #     working_directory: ~/cypress-tutorial-build-todo-starter
          # command: npm install --save-dev cypress
      - run: 
          working_directory: ~/cypress-tutorial-build-todo-starter
          command: ./node_modules/.bin/cypress run
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
