# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      ## background your server
      - run: npm start wait-on http://localhost:3030
      - run: npm install --save-dev cypress
      - run: $(npm bin)/cypress verify
      - run: $(npm bin)/cypress run
